### ISSUE TITLE
No working HTML document without.

### ISSUE THREAD

**Issue by Veicm** [theNetworkChuck/chuckblog#4]
I'm not sure if this is the right place for that question but after I followed the steps in the YouTube video I found this issue: When I launch the website in local host everything works fine but when I deploy the index.html file I see all Informations but not the theme, It looks a bit like a html document without a css document. And that's important for me because I want to bind the Blog to my existing website wich runs on GitHub pages that's why I need a working .html file. If someone knows how to fix this issue I would be very thankfully.

**Comment by JBraunsmaJr** [comment]
If this sounds like your problem, here's the fix.

You launch the "built" version somewhere and all you see is a lovely white page with no CSS.

Sounds like a baseUrl issue.

Navigate to your `hugo.toml` and change that value. For GitHub pages this value (when deployed at least) should match the name of the repository, `/chuckblog` for instance (if we use THIS repo as an example).

You can verify things in your browser by opening up the console and network tabs to view the errors. Note the URLs they're trying to pull from. This can help you figure out the pathing issue.

**Comment by theNetworkChuck** [comment]
Hello,

My name is Mikayla, I am part of the NC team. Thanks for reaching out, for
any questions we do want to encourage you to use our discord as there are a
lot of people who would love to help you there! Here is the link:
https://discord.gg/networkchuck

Hope this helps,
Mikayla

**Comment by Veicm** [comment]
Thank you but I already solved my problem but I will remember for the next one.
